blank_issues_enabled: true
contact_links:
  - name: Discuss general Dashlane CLI question or issue
    url: https://github.com/Dashlane/dashlane-cli/discussions/new/choose
    about: We use Discussions for asking questions or getting help on your own projects and integration
